/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CompareImport } from './routes/compare'
import { Route as IndexImport } from './routes/index'
import { Route as PlayersIndexImport } from './routes/players.index'
import { Route as PlayersPlayerNameImport } from './routes/players.$playerName'
import { Route as ClubsClubTagImport } from './routes/clubs.$clubTag'

// Create/Update Routes

const CompareRoute = CompareImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayersIndexRoute = PlayersIndexImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRoute,
} as any)

const PlayersPlayerNameRoute = PlayersPlayerNameImport.update({
  id: '/players/$playerName',
  path: '/players/$playerName',
  getParentRoute: () => rootRoute,
} as any)

const ClubsClubTagRoute = ClubsClubTagImport.update({
  id: '/clubs/$clubTag',
  path: '/clubs/$clubTag',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareImport
      parentRoute: typeof rootRoute
    }
    '/clubs/$clubTag': {
      id: '/clubs/$clubTag'
      path: '/clubs/$clubTag'
      fullPath: '/clubs/$clubTag'
      preLoaderRoute: typeof ClubsClubTagImport
      parentRoute: typeof rootRoute
    }
    '/players/$playerName': {
      id: '/players/$playerName'
      path: '/players/$playerName'
      fullPath: '/players/$playerName'
      preLoaderRoute: typeof PlayersPlayerNameImport
      parentRoute: typeof rootRoute
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/clubs/$clubTag': typeof ClubsClubTagRoute
  '/players/$playerName': typeof PlayersPlayerNameRoute
  '/players': typeof PlayersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/clubs/$clubTag': typeof ClubsClubTagRoute
  '/players/$playerName': typeof PlayersPlayerNameRoute
  '/players': typeof PlayersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/clubs/$clubTag': typeof ClubsClubTagRoute
  '/players/$playerName': typeof PlayersPlayerNameRoute
  '/players/': typeof PlayersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/clubs/$clubTag'
    | '/players/$playerName'
    | '/players'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compare' | '/clubs/$clubTag' | '/players/$playerName' | '/players'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/clubs/$clubTag'
    | '/players/$playerName'
    | '/players/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ClubsClubTagRoute: typeof ClubsClubTagRoute
  PlayersPlayerNameRoute: typeof PlayersPlayerNameRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ClubsClubTagRoute: ClubsClubTagRoute,
  PlayersPlayerNameRoute: PlayersPlayerNameRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/compare",
        "/clubs/$clubTag",
        "/players/$playerName",
        "/players/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/compare": {
      "filePath": "compare.tsx"
    },
    "/clubs/$clubTag": {
      "filePath": "clubs.$clubTag.tsx"
    },
    "/players/$playerName": {
      "filePath": "players.$playerName.tsx"
    },
    "/players/": {
      "filePath": "players.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
