/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ClubsClubTagImport } from './routes/clubs.$clubTag'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ClubsClubTagRoute = ClubsClubTagImport.update({
  id: '/clubs/$clubTag',
  path: '/clubs/$clubTag',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/clubs/$clubTag': {
      id: '/clubs/$clubTag'
      path: '/clubs/$clubTag'
      fullPath: '/clubs/$clubTag'
      preLoaderRoute: typeof ClubsClubTagImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clubs/$clubTag': typeof ClubsClubTagRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clubs/$clubTag': typeof ClubsClubTagRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/clubs/$clubTag': typeof ClubsClubTagRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clubs/$clubTag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clubs/$clubTag'
  id: '__root__' | '/' | '/clubs/$clubTag'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubsClubTagRoute: typeof ClubsClubTagRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubsClubTagRoute: ClubsClubTagRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/clubs/$clubTag"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/clubs/$clubTag": {
      "filePath": "clubs.$clubTag.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
